# Generated by Django 5.1.1 on 2024-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=15)),
                ('lastName', models.CharField(blank=True, max_length=15)),
                ('companyName', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('messageText', models.TextField()),
            ],
        ),
    ]
