# Generated by Django 5.1.1 on 2024-09-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageRead',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
