# Generated by Django 5.1.1 on 2024-09-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=150)),
                ('productImage', models.ImageField(blank=True, default='fallbackimg.jpg', upload_to='')),
                ('info1', models.CharField(blank=True, max_length=100)),
                ('info2', models.CharField(blank=True, max_length=100)),
                ('info3', models.CharField(blank=True, max_length=100)),
                ('info4', models.CharField(blank=True, max_length=100)),
                ('info5', models.CharField(blank=True, max_length=100)),
                ('info6', models.CharField(blank=True, max_length=100)),
                ('info7', models.CharField(blank=True, max_length=100)),
                ('info8', models.CharField(blank=True, max_length=100)),
                ('info9', models.CharField(blank=True, max_length=100)),
                ('info10', models.CharField(blank=True, max_length=100)),
                ('info11', models.CharField(blank=True, max_length=100)),
                ('info12', models.CharField(blank=True, max_length=100)),
                ('info13', models.CharField(blank=True, max_length=100)),
                ('info14', models.CharField(blank=True, max_length=100)),
                ('info15', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('barndName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brand.brands')),
            ],
        ),
    ]
