# Generated by Django 5.1.1 on 2024-10-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=150)),
                ('info1', models.CharField(blank=True, max_length=200)),
                ('info2', models.CharField(blank=True, max_length=200)),
                ('info3', models.CharField(blank=True, max_length=200)),
                ('info4', models.CharField(blank=True, max_length=200)),
                ('info5', models.CharField(blank=True, max_length=200)),
                ('info6', models.CharField(blank=True, max_length=200)),
                ('info7', models.CharField(blank=True, max_length=200)),
                ('info8', models.CharField(blank=True, max_length=200)),
                ('info9', models.CharField(blank=True, max_length=200)),
                ('info10', models.CharField(blank=True, max_length=200)),
                ('info11', models.CharField(blank=True, max_length=200)),
                ('info12', models.CharField(blank=True, max_length=200)),
                ('info13', models.CharField(blank=True, max_length=200)),
                ('info14', models.CharField(blank=True, max_length=200)),
                ('info15', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('productImage', models.ImageField(default='fallback.jpg', upload_to='')),
                ('barndName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brands')),
                ('categoryTitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='typeTitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.type'),
        ),
    ]
