# Generated by Django 5.1.1 on 2024-10-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
