# Generated by Django 5.1.1 on 2024-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='info1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info13',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info14',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info15',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='info9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
    ]
