# Generated by Django 5.1.1 on 2024-09-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_info1_alter_products_info10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(default='fallback.jpg', upload_to=''),
        ),
    ]
