# Generated by Django 5.1.1 on 2024-10-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_category_typetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='typeTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=30, unique=True),
        ),
    ]
